#!/usr/bin/env sh

XXX=${1:-n}

#https://unix.stackexchange.com/questions/286721/get-wi-fi-interface-device-names
# echo /sys/class/net/*/wireless | awk -F'/' '{ print $5 }'
INTERFACE=$(echo /sys/class/net/*/wireless | awk -F'/' '{ print $5 }')

usage() {
  echo use with parsimony
  #TODO: add a serious message
}

get_interface_name() {
  echo $INTERFACE
}

get_channels() {
  sudo iwlist $INTERFACE scan | grep \(Channel
}

restart_network() {
  sudo killall NetworkManager
  sleep 1
  sudo NetworkManager
}

excute() {
  case $XXX in
  -c) get_channels ;;
  -n) get_interface_name ;;
  -r) restart_network ;;
  -h | *) usage ;;
  esac
}

excute
