#!/usr/bin/env sh

. x-utils

# https://github.com/FilenCloudDienste/filen-rs/blob/main/filen-cli/install.sh

update_distro() {
  log ${WARNING_SIGN} ${BOLD_PURPLE} "Distro updates" ${COLOR_OFF}
  if [[ $(command -v eopkg) ]]; then # Solus
    #https://linuxiac.com/solus-linux-eopkg-package-manager-guide/
    output=$(sudo eopkg upgrade -n)
    string="No packages to upgrade"
    # if [[ "$output" =~ "No packages to upgrade" ]]
    if [[ $(sudo eopkg upgrade -n) =~ "No packages to upgrade" ]]
    then
      log ${CROSS_MARK} ${YELLOW} "No distro updates available" ${COLOR_OFF}
    else
      sudo eopkg upgrade
      sudo eopkg delete-cache
      log ${CHECK_MARK} ${GREEN} "Distro updated! 🥳🎉" ${COLOR_OFF}
    fi
  elif [[ $(command -v swupd) ]]; then # ClearLinux
    sudo swupd update
  fi
  # Serpent OS

}

update_dotfiles() {
  log ${WARNING_SIGN} ${BOLD_PURPLE} "Dotfiles update" ${COLOR_OFF}
  list=("$@")

  for repo_name in "${list[@]}"; do
    cd $XDG_CONFIG_HOME/${repo_name}
    echo -e "\t$PWD\n\tChecking if ${repo_name} is up-to-date, otherwise pulling updates."
    git pull
  done
  log ${CHECK_MARK} ${GREEN} "Dotfiles updated! 🥳🎉" ${COLOR_OFF}
}

update_fisher() {
  log ${WARNING_SIGN} ${BOLD_PURPLE} "Fisher update" ${COLOR_OFF}

  FISHER_INSTALLED_VERSION=$(fish -c 'fisher -v' | cut -d' ' -f3)
  FISHER_REMOTE_VERSION=$(curl -s https://api.github.com/repos/jorgebucaran/fisher/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | cut -c1-)
  
  if [[ ${FISHER_REMOTE_VERSION} == "" ]] ; then
    log ${CROSS_MARK} ${RED} "Check Fisher latest URL" ${COLOR_OFF}
    exit 1
  fi
  
  if [ $(version $FISHER_INSTALLED_VERSION) -lt $(version $FISHER_REMOTE_VERSION) ]; then
    # echo -e "Updating fisher to ${FISHER_REMOTE_VERSION}"
    log ${WARNING_SIGN} ${YELLOW} "Updating fisher to ${FISHER_REMOTE_VERSION}" ${COLOR_OFF}
  else
    # echo "Installed version (${FISHER_INSTALLED_VERSION}) is up to date (remote is ${FISHER_REMOTE_VERSION})"
    log ${CHECK_MARK} ${GREEN} "Installed version (${FISHER_INSTALLED_VERSION}) is up to date (remote is ${FISHER_REMOTE_VERSION})" ${COLOR_OFF}
  fi
  #TODO: fix this
  fish -c "fisher update"
  log ${CHECK_MARK} ${GREEN} "Fisher updated!" ${COLOR_OFF}
}

update_fonts() {
  log ${WARNING_SIGN} ${BOLD_PURPLE} "Fonts update" ${COLOR_OFF}
  echo -e "\n--- to be implemented yet\n"
  log ${CHECK_MARK} ${GREEN} "Fonts updated!" ${COLOR_OFF}
}

update_flatpak() {
  log ${WARNING_SIGN} ${BOLD_PURPLE} "Flatpak update" ${COLOR_OFF}
  flatpak update -y
  log ${CHECK_MARK} ${GREEN} "Flatpak updated!" ${COLOR_OFF}
}

update_kitty() {
  log ${WARNING_SIGN} ${BOLD_PURPLE} "Kitty update" ${COLOR_OFF}
  
  REMOTE_VERSION=`curl -s https://api.github.com/repos/kovidgoyal/kitty/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | cut -c2-`
  INSTALLED_VERSION=$(kitty -v 2>&1 | cut -d ' ' -f2)

  if [[ ${REMOTE_VERSION} == "" ]] ; then
    log ${CROSS_MARK} ${RED} "Check Kitty latest URL" ${COLOR_OFF}
    exit 1
  fi
  if [ $(version $INSTALLED_VERSION) -lt $(version $REMOTE_VERSION) ]; then
    log ${WARNING_SIGN} ${YELLOW} "Updating Kitty to ${REMOTE_VERSION})" ${COLOR_OFF}
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
    log ${CHECK_MARK} ${GREEN} "Updated Kitty to version ${REMOTE_VERSION})" ${COLOR_OFF}
  else
    log ${CHECK_MARK} ${GREEN} "Installed version (${INSTALLED_VERSION}) is up to date (remote is ${REMOTE_VERSION})" ${COLOR_OFF}
  fi
}

update_nix() {
  # log "Nix update. This can take a while ☕🛋️💤"
  log ${WARNING_SIGN} ${BOLD_PURPLE} "Nix update. This can take a looong while ☕🛋️💤" ${COLOR_OFF}

  #TODO: temp fix
  nix-channel --update
  nix-env -u &>/dev/null
  log ${CHECK_MARK} ${GREEN} "Nix packages updated! 🥳🎉" ${COLOR_OFF}

  #FIX: no useful output?
  # if [[ $(nix-channel --update 2>&1) =~ "switching from generation" ]]
  # then
    #https://nix.dev/manual/nix/2.22/command-ref/nix-channel
    # nix-channel --update

    #https://nix.dev/manual/nix/2.22/command-ref/nix-env/upgrade
    # nix-env -u &>/dev/null
    #nix-channel --list-generations
    
    # log "Nix packages updated! 🥳🎉"
  # else
    # log "No Nix updates available."
  # fi
}

setup_vimix_themes() {
  REMOTE_VERSION=`curl -s https://api.github.com/repos/vinceliuice/${1}/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | cut -c1-`
  FILE_INSTALLED_VERSION=$HOME/.themes/.${1}
  if [[ -f  $FILE_INSTALLED_VERSION ]];then

  INSTALLED_VERSION=$(cat $FILE_INSTALLED_VERSION)
  else
    INSTALLED_VERSION=0
  fi

  if [ $(version $INSTALLED_VERSION) -lt $(version $REMOTE_VERSION) ]; then
    REPO=https://github.com/vinceliuice/${1}
    log ${WARNING_SIGN} ${YELLOW} "Updating ${1} (current version ${INSTALLED_VERSION}) to ${REMOTE_VERSION})" ${COLOR_OFF}
    cd /tmp/
    if [[ -d $1 ]];then
      log "/tmp/$1 already exists! Deleting folder and cloning the ${REPO}"
      rm -Rf /tmp/$1
    fi

    git clone ${REPO}
    cd /tmp/${1}

    if [[ $1 =~ Vimix-gtk-themes ]]; then
      echo Vimix-gtk-themes
      ./install.sh -t all -s all
    fi
    if [[ $1 =~ Vimix-icon-theme ]]; then
      echo Vimix-icon-theme
      ./install.sh -a
      echo "${REMOTE_VERSION}" > $HOME/.themes/.${1}
    log ${CHECK_MARK} ${GREEN} "${1} themes update!" ${COLOR_OFF}
    fi
  else
    log ${CHECK_MARK} ${GREEN} "${1} themes already up-to-date!" ${COLOR_OFF}
  fi
}

update_themes() {
  log ${WARNING_SIGN} ${BOLD_PURPLE} "Themes update" ${COLOR_OFF}
  setup_vimix_themes Vimix-gtk-themes
  setup_vimix_themes Vimix-icon-theme
  log ${CHECK_MARK} ${GREEN} "Themes updated!" ${COLOR_OFF}
}

execute() {
  # TODO: user choice
  log ${WARNING_SIGN} ${BOLD_PURPLE} "System updates" ${COLOR_OFF}
  update_distro
  update_flatpak
  update_nix
  update_dotfiles
  update_kitty
  update_fisher
  update_fonts
  update_themes
}

execute

