#!/usr/bin/env sh
echo -e "--- System update"

version() { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }

update_distro() {
  if [[ $(command -v eopkg) ]]; then # Solus
    sudo eopkg upgrade
  elif [[ $(command -v swupd) ]]; then # ClearLinux
    sudo swupd update
  fi
  # Serpent OS
}

update_dotfiles() {
  list=("$@")

  for repo_name in "${list[@]}"; do
    cd $XDG_CONFIG_HOME/${repo_name}
    echo -e "\t$PWD\n\tChecking if ${repo_name} is up-to-date, otherwise pulling updates."
    git pull
  done
}

update_fisher() {
  FISHER_INSTALLED_VERSION=$(fish -c 'fisher -v' | cut -d' ' -f3)
  FISHER_REMOTE_VERSION=$(curl -s https://api.github.com/repos/jorgebucaran/fisher/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | cut -c1-)

  if [ $(version $FISHER_INSTALLED_VERSION) -lt $(version $FISHER_REMOTE_VERSION) ]; then
    echo -e "Updating fisher to ${FISHER_REMOTE_VERSION}"
    setup_config
    fish -c fisher update
  else
    echo "Installed version (${FISHER_INSTALLED_VERSION}) is up to date (remote is ${FISHER_REMOTE_VERSION})"
  fi
}

update_fonts() {
  echo -e "\n--- to be implemented yet\n"
}

update_flatpak() {
  flatpak update
}

update_kitty() {
  INSTALLED_VERSION=$(kitty -v 2>&1 | cut -d ' ' -f2)
  REMOTE_VERSION=`curl -s https://api.github.com/repos/kovidgoyal/kitty/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | cut -c2-`
  if [ $(version $INSTALLED_VERSION) -lt $(version $REMOTE_VERSION) ]; then
    echo -e "Updating Kitty to ${REMOTE_VERSION}"
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  else
    echo "Installed version (${INSTALLED_VERSION}) is up to date (remote is ${REMOTE_VERSION})"
  fi
}

update_nix() {
  nix-channel --update
  nix-env -u
}

setup_vimix_themes() {
  REMOTE_VERSION=`curl -s https://api.github.com/repos/vinceliuice/${1}/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | cut -c2-`
  INSTALLED_VERSION=$(cat $HOME/.themes/${1})
  if [ $(version $INSTALLED_VERSION) -lt $(version $REMOTE_VERSION) ]; then
    echo -e "Updating ${1} (current version ${INSTALLED_VERSION}) to ${REMOTE_VERSION}"
    cd /tmp/
    rm -Rf /tmp/${1}.zip 2>/dev/null
    rm -Rf /tmp/${1}-master/ 2>/dev/null
    wget https://github.com/vinceliuice/${1}/archive/master.zip -O ${1}.zip
    unzip ${1}.zip
    cd ${1}-master
    ./install.sh
    echo "${REMOTE_VERSION}" > $HOME/.themes/.${1}
  fi
}

update_themes() {
  setup_vimix_themes vimix-gtk-themes
  setup_vimix_themes vimix-icon-theme
}

execute() {
  # TODO: user choice
  update_distro
  update_dotfiles
  update_fisher
  update_flatpak
  update_fonts
  update_nix
  update_kitty
  update_themes
}

execute

